[versions]
agp = "8.1.0"
kotlin = "1.9.0"
publish = "0.21.0"
grease = "0.3.2"

[plugins]
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
grease = { id = "io.deepmedia.tools.grease", version.ref = "grease" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

